export const INFERENCE_WEIGHTS = {
  MANUFACTURING_COUNTRY: 0.6,
  PURCHASE_COUNTRY: 0.6,
  LANGUAGE: 0.25,
  LABEL: 0.85,
  BARCODE_PREFIX: 0.05,
} as const;

export const MINIMUM_CONFIDENCE_THRESHOLD = 0.15;